name: Format
on:
  push:
    branch:
      - main
    paths:
      - '**.go'
  pull_request:
    paths:
      - '**.go'
jobs:
  go-fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check files for wrong formatting
        run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi
